FROM ubuntu:bionic

RUN apt-get update && apt-get install -y ethtool curl iproute2 net-tools iputils-ping dnsutils vim-tiny

# Spoiler alert!
# Invalid host file entry prevents DNS lookup, need to delete this entry
CMD exec /bin/sh -c "trap : TERM INT; echo '1.2.3.4 server' >> /etc/hosts; sleep infinity & wait"
