version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    cap_add:
      - NET_ADMIN
    depends_on:
      - server
